### ISSUE TITLE
Modify the data structure of chemical

### ISSUE THREAD

**Issue by hngskj** [labnote-ant/labnote#85]
Before:
```yaml
new_chemical: {
    id: null,
    type: "chemical",
    nickname: null,
    additional: "",
    ingredients: [
      {
        id: uuid(),
        name: "",
        product_number: "",
        state: "",
        solvent: "",
        volume: null,
        v_unit: "",
        concentration: null,
        c_unit: "",
        weight: null,
        w_unit: "",
        pressure: null,
        p_unit: "",
        property: [],
      },
    ],
  },
```

After:
```yaml
new_chemical_edited: {
    id: null,
    type: "chemical",
    additional: "",
    info: {
      display: "", // whatever a user inputs (name or formula)
      nickname: null,
      product_number: "",
      amount: "", // 25uL or 40kg
      state: "", // solid, solution, liquid, gas, mixed(mixed, added, injected)
      volume: "", // solution & gas
      weight: "", // solid & liquid
      solvent: "", // solution
      concentration: "", // solution
      pressure: "", // gas
      property: [],
      sources: [], // source chemicals from inputs of Mix, Add, and Inject
    },
  },
```

Example 1:
```yaml
example: {
          id: "s1_c1",
          type: "chemical",
          additional: "This is my memo.",
          info: {
            display: "AgNO3",
            nickname: null,
            product_number: "7d8yav",
            amount: "",
            state: "solution",
            volume: "250uL",
            weight: null,
            solvent: "water",
            concentration: "15mM",
            pressure: null,
            property: [],
            sources: [],
          },
        },
```
Example 2:
```javascript
new_chemical_example2: {
    id: "t34g34tsg",
    type: "chemical",
    additional: "Hello there :)",
    info: {
      display: "hello + PSSS + NaBH4",
      nickname: "precursor",
      product_number: null,
      amount: "300mL",
      state: "compound",
      concentration: null,
      pressure: null,
      property: ["mixed"],
      sources: [
        {
          id: "28fhiwef", // display: "AgNO3", nickname: "hello"
          amount: "11mL"
        },
        {
          id: "34g738fs", // display: "PSSS", nickname: null
          amount: "50uL"
        },
        {
          id: "29834u938", // display: NaBH4, nickname: null
          amount: "2uL"
        }
      ],
    },
  },
```
